apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uhwc0kc02-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-810e0203e5.chle.p3.openshiftapps.com/rhtap/rhtap-qe:1292787e7ec60b8b8411fc7feb3a808f6c21d625@sha256:79403ff4cbfce13e7799eda7dee18822bd9ce396975de28159bf8de5954f91b7
          name: container-image
