apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uhwc0kc02-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uhwc0kc02-java-quarkus-gitops